apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-app
  namespace: shine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retail-app
  template:
    metadata:
      labels:
        app: retail-app
    spec:
      containers:
      - name: retail-app
        image: dalalappagariajithkumar/shine-app:v1
        ports:
        - containerPort: 3130
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-deployment:27017/myDatabase"
        - name: SESSION_SECRET
          value: "1234"
        - name: PORT
          value: "3130"
